### ISSUE TITLE
Membershipの有効性

### ISSUE THREAD

**Issue by SamuraiT** [henkaku-center/podcast-nft#12]
## 目的
- memebrshipのtransferを防ぐ

## 実現方法
- もしonwerとtransferしたaddressが違う場合に、attributesにnot validをつける
- もしくは、transferできないようにする

## 懸念
- transferされて新しい使われ方があるかもしれないので、その可能性を奪うこと

**Comment by geeknees** [comment]
https://github.com/henkaku-center/podcast-nft/issues/21

I think we can resolve it [here](https://github.com/henkaku-center/podcast-nft/issues/21), so I'll close this.
