### ISSUE TITLE
burn(admin can burn NFTs of others)

### ISSUE THREAD

**Issue by geeknees** [henkaku-center/podcast-nft#21]
https://app.dework.xyz/henkaku/podcast-nft?taskId=9870242e-8f31-452a-ae1b-3fe94798ad21’

## 目的
- コミュニティ外の人に membership NFT が渡ったときにアドミンがburnして無効化できるようにしたい

## 前提情報
- 0x000000000000000000000000000000000000dead に送ることを burn すると呼ぶ
- 0x000000000000000000000000000000000000dead は誰も操作できないアドレスとなっており、そこに送ると誰も操作できない＝無効化できる

## 実装方針

現状アイディは3通り出ている
1.  burn  と呼びつつ 0x000000000000000000000000000000000000dead には送らないで無効化の処理を入れる
2. 0x000000000000000000000000000000000000dead に送るようにする
3. 任意のアドレスに送れるようにする

定例ミーティングで議論した方向性は burn と呼ぶむのであれば 2 または 3 の方向性が良いのではということになっている

- 実装者が適宜判断をしてコミュニティ内でレビューをして確定することを想定
- 管理者権限管理については https://github.com/henkaku-center/podcast-nft/issues/19 で実装されるのでこのISSUEではrequire の部分のみ実装すればOK
- 実際のロジックは自分で書くひつようあり

**Comment by hourglasshoro** [comment]
ロジックの実装について相談です。PodCastNFTはERC721URIStorage、ERC721URIStorageはERC721を継承していると思います。なので、ERC721の_burn()の実装を参考にして、PodCastNFTのburn()で同じように定義しようと思ったのですが、ERC721に定義してあるprivate変数の_balancesなどを操作する必要があり、それが操作できそうなメソッドもなさそうだったので、単純にPodCastNFTのburn()でERC721URIStorageの_burn()を呼ぶ感じになりそうです。

ちなみにERC721とERC721URIStorageの_burn()は以下のようになっているのですが、address(0)は`0x000000000000000000000000000000000000dead`ではない認識なのですが、この認識はあってますか？この場合、どう実装するのがいいんでしょうか

```
// ECR721
    function _burn(uint256 tokenId) internal virtual {
        address owner = ERC721.ownerOf(tokenId);

        _beforeTokenTransfer(owner, address(0), tokenId);

        // Clear approvals
        _approve(address(0), tokenId);

        _balances[owner] -= 1;
        delete _owners[tokenId];

        emit Transfer(owner, address(0), tokenId);
    }

// ERC721URIStorage
    function _burn(uint256 tokenId) internal virtual override {
        super._burn(tokenId);

        if (bytes(_tokenURIs[tokenId]).length != 0) {
            delete _tokenURIs[tokenId];
        }
    }
```

**Comment by geeknees** [comment]
@hourglasshoro 

はい実装のイメージあっているかと思います。書きあたりの実装も参考になるかもです。
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5a75065659a65e65bb04890192e3a4bcb7917fff/contracts/token/ERC721/extensions/ERC721Burnable.sol#L21

関数名もburnを使うのが良いのか、それっぽい名前にするのかも適宜判断いただいて構いません。

address(0) は `0x0000000000000000000000000000000000000000` を指しているのでこちらで問題ないと思います。

burnは`0x000000000000000000000000000000000000dead` または`0x0000000000000000000000000000000000000000` で構いません。情報が漏れていました。すみません。

https://etherscan.io/address/0x000000000000000000000000000000000000dead
https://etherscan.io/address/0x0000000000000000000000000000000000000000

調べてみてわかったのですが、25アドレスほど用意さ入れているようです。
https://etherscan.io/accounts/label/burn

丁寧に調べていただきありがとうございますー

**Comment by SamuraiT** [comment]
@hourglasshoro 
そもそもopenzepplinのERC721で提供されていて
```js
function burn(....) ...{
 _burn(tokenId)
}
```
とするだけで十分だと思います。

**Comment by hourglasshoro** [comment]
https://github.com/henkaku-center/podcast-nft/pull/33

**Comment by hourglasshoro** [comment]
このissueは完了としてcloseしてもいいんでしょうか？Dework側のチケットもあると思うんですがin reviewにする形でしょうか？

**Comment by geeknees** [comment]
はい！閉じちゃいます！deworkの方も支払い待ちの方に移動させちゃいます。フォローありがとうございます！

**Comment by hourglasshoro** [comment]
ありがとうございます🙇‍♂️
