### ISSUE TITLE
IERC721Enumerable totalSupplyの実装

### ISSUE THREAD

**Issue by geeknees** [henkaku-center/podcast-nft#22]
https://app.dework.xyz/henkaku/podcast-nft?taskId=72d6d5dd-1031-4da3-9fc6-0503a7348e28

## 目的

- membership NFT にて totalSupply function を実装することによって、会員権を持っているかどうかの判定ロジックを実装しやすくしたい
- totalSupply を実装すると、現在いくつNFTが発行されているかコントラクトに問い合わせができる
- ない場合は、暗黙的に1000回分ループを回すなどの実装になる

## 解決策
- totalSupply は OpenZeppelin がライブラリを用意してくれているのでこれを使うのが良い 
- https://docs.openzeppelin.com/contracts/3.x/api/token/erc721#IERC721Enumerable

 ## 参考情報
- https://ethereum.stackexchange.com/questions/112271/implementing-ierc721enumerable-interface

**Comment by RyuKiyo66** [comment]
totalSupply()を実装するとは、
totalSupply()が含まれる、ERC721Enumerableのlibraryをimportするってことでしょうか？
import "@openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol";
これで、
このlibraryの中ですでに、
    function totalSupply() external view returns (uint256);
が定義されていると理解すれば良いのでしょうか？
externalであるということは、これを他のコントラクトやフロントエンドなどから呼び出し、発行済のNFTのtoken番号1からtotalSupply()まで繰り返し、総当たり的に、msg.senderで得たアドレスと発行済のNFTのアドレスを比較し、一致するものがない時にミントするということでしょうか？

**Comment by geeknees** [comment]
@RyuKiyo66 

はい！3つの質問全て、認識あっているかと思います。

補足するとimportしたあと、下記のところで継承関係として定義して上げる必要があるかと思います。
https://github.com/henkaku-center/podcast-nft/blob/6b1e61df284b6344d1132e85237441e02e9c33f8/contracts/PodCastNFT.sol#L12

また、動作確認としてtotalSupply()が本当に呼べるか確認するためには2つ方法があって
1. テストコードを書く
  - https://github.com/henkaku-center/podcast-nft/blob/6b1e61df284b6344d1132e85237441e02e9c33f8/test/mint.js#L14
2. スクリプトで動作確認をする
  - https://github.com/henkaku-center/podcast-nft/blob/main/scripts/mint.js 
のどちらかです。

**Comment by RyuKiyo66** [comment]
importと継承は、Forkした自分のレポジトリに反映済みです。
一方、テストコードは、例えば、totalSupply()を表示するようにするということでしょうか？
スクリプトの動作確認は、自分のPCにクローンを作って、やってみるということでしょうか？

**Comment by geeknees** [comment]
@RyuKiyo66 

はい。下記の変更ですよね。こちらでそのままPRを出してもらうのでも大丈夫です。
https://github.com/RyuKiyo66/podcast-nft-1/commit/8432756e66461bca78f1a23e76c3365448ffaf66

PRを出すときの注意点ですが、mainではなく開発中のmembership-nft-v2に対して出していただけるとありがたいです。
<img width="1338" alt="スクリーンショット 2022-04-24 11 14 11" src="https://user-images.githubusercontent.com/701242/164953111-096461a7-12ae-48f5-b8d5-098a640e8e93.png">

テストコードについては別で対応でも構いませんが、一応やり方は下記のとおりです。
スクリプトの動作確認はテストで対応するほうが好ましいのでテストをやる場合は無しで良いので割愛します。

例えば下記のところがテストコードです。
https://github.com/henkaku-center/podcast-nft/blob/6b1e61df284b6344d1132e85237441e02e9c33f8/test/mint.js#L14

コントラクトをデプロイして、mint して、デプロししたオーナーが意図としたものになっているかチェックしています。
totalSupply に関しては mint して、totalSupplyが増えていれば（1になっていれば）テストできていると思います。

テストを実行するのには手元のターミナルで下記のコメントを打つと実行できます。

`npx hardhat test`

分からなければ聞いてください！テストはいったんなくても大丈夫です。後で僕の方で追加することもできます。

**Comment by RyuKiyo66** [comment]
@geeknees 
お忙しいところありがとうございます。
ひとまず、みなさまのご迷惑にならないように、テストは別途私もやってみるとして、PRまずします。
